[package]
name = "bridge-shared"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.80"
delegate = "0.12.0"
derive_more = { workspace = true, features = ["deref"] } 
futures.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
test-log = { version = "0.2.16", features = ["trace"] }
tokio.workspace = true

[lints]
workspace = true
