[package]
name = "bridge-shared"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.80"
delegate = "0.12.0"
derive_more = { workspace = true, features = ["deref", "deref_mut"] } 
futures.workspace = true
futures-timer = "3.0.3"
thiserror.workspace = true
tracing.workspace = true
rand.workspace = true
rand_chacha = "0.2.2"
futures-time = "3.0.0"

[dev-dependencies]
dashmap = "6.0.1"
static_str_ops = "0.1.2"
test-log = { version = "0.2.16", features = ["trace"] }
tokio.workspace = true

[lints]
workspace = true
